name: loki
description: Loki is a command-line interface (CLI) tool designed for managing Dart and Flutter projects featuring multiple packages.
version: 0.1.0
repository: https://github.com/cybertronbaka/loki
homepage: https://github.com/cybertronbaka/loki
issue_tracker: https://github.com/cybertronbaka/loki/issues
documentation: https://pub.dev/documentation/loki/latest/

environment:
  sdk: ^3.1.3

dependencies:
  yaml: ^3.1.2
  chalkdart: ^2.0.9
  args: ^2.4.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

executables:
  loki: loki

topics:
  - packages
  - workspace
