name: loki
description: A starting point for Dart libraries or applications.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  yaml: ^3.1.2
  chalkdart: ^2.0.9
  args: ^2.4.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

executables:
  loki: loki