name: Dart

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.7'
          channel: 'stable'
      - run: dart pub get
      - run: dart analyze
      - run: dart pub global activate --source path . --overwrite
      - run: loki run test:validate